### ISSUE TITLE
Equipment not showing up when choosing what to hold in hands

### ISSUE THREAD

**Issue by TheFabulousIronChef** [StefanLeng/gurps-categorized-sheet#1]
This looks quite cool so far. Tried it on three characters I have in a solo adventure game. The ability to assign what's in someone's hand is very cool. Was able to do it with my scout (Composite Bow) and by Swashbuckler (saber in each hand), but with my Knight, I cannot assign her anything--not her morningstar, shield, or any other weapons. See the image below. They're all imported from GCS and should all be the same, and yet...can't seem to get anything other than "empty hand." 

![image](https://github.com/user-attachments/assets/803a8b46-215c-41e8-a9db-eabe74317736)

**Comment by StefanLeng** [comment]
Thak you for the feedback.  
It seem the sheet cann not find the  weapons or the associated attacks, thats odd. Can you attacht the GCS file for the character?
I assume the weapon attacks show up normaly on the standard GGA sheet. Can you show a screenshot of the melee atacks on the  standard sheet? 
Have you the option "Remove unequipped wepons from melee und ranged list" activated in de GGA Options?

**Comment by StefanLeng** [comment]
Another thing I just noticed: From the modifieres it seems he has Combat Reflexes. If so, it should show up in an advantages/disadvantages  block below the  skills. Is is missing completly or is listed on the  Others tab?

**Comment by TheFabulousIronChef** [comment]
I’ll send shortly once I’m in front of a computer.

Dictated and sent from my iPhone

**Comment by StefanLeng** [comment]
One more questions: Did you have "Use foundry items for player data" turned on when you imported the character. My sheet seems to be broken with this setting ...

**Comment by TheFabulousIronChef** [comment]
I didn't have "Use foundry items for player data" turned on (never knew it existed until recently)
Combat reflexes (and all advantages) show up under Other
Github doesn't like uploading GCS files apparently, so I'll put it in Discord. 

![image](https://github.com/user-attachments/assets/6ef31aef-4c1c-4bf3-b128-40666a8f7f19)
![image](https://github.com/user-attachments/assets/fae66419-18ac-4bc1-9702-376b712a6fcc)
![image](https://github.com/user-attachments/assets/59e78bb8-d411-4c81-a224-3286b3e60224)

**Comment by StefanLeng** [comment]
My mod dosn't find the weapon, beacuse it is in a container. Should be easily fixabel.

More interesting is the issue with the advantages: They are in containers, too. At the moment, I just sort the containers, so everything shows up on Others. Maybe I should display the containers on each tab where at least one content matches, but only with the matchin content? What do you think?

**Comment by StefanLeng** [comment]
Weapon issue fixed with 0.3.1.
Will have to thing about waht to do with skills and advantages in contianers.

**Comment by StefanLeng** [comment]
Traits in containers handled in 0.3.2
