### ISSUE TITLE
Bug: Categorized Sheet doesn't allow you to use a two-handed weapon with one hand if you meet the strength requirement to do so

### ISSUE THREAD

**Issue by PrinceOfIonia** [StefanLeng/gurps-categorized-sheet#10]
Exactly as title says, here is the GCS file: 
[GCS File.zip](https://github.com/user-attachments/files/17950281/GCS.File.zip)

**Comment by StefanLeng** [comment]
I will implement that (if the GGA data model lets me do it, but I think so), but propably make it an option.

This rule can get really wierd if you have a weapon that has both one-handed and two-handed weapon modes, like the Basdard Sword. Can you really wield it one-handed using the Two-handed weapon skill if you have enough strength?  But if not, why can you do it with a Greatsword? 

As a GM, I would propably make custom weapon stats for such a character, that uses the Greatsword stats but the Browdsword skill, but that's just me.

**Comment by PrinceOfIonia** [comment]
I suppose as long as you do not restrict players from rolling whatever weapon they want regardless if they have it "equipped" or not then its fine.

**Comment by StefanLeng** [comment]
Implemented in 0.4.1. You need to activate it in the module setting (or per character in the sheet settings).
