### ISSUE TITLE
Bug: Move doesn't appear to be shown correctly.

### ISSUE THREAD

**Issue by PrinceOfIonia** [StefanLeng/gurps-categorized-sheet#12]
![image](https://github.com/user-attachments/assets/f6569758-8390-4dc0-8432-30c542abb1e4)
This is what I see, it seems bugged to me.

[GCS File.zip](https://github.com/user-attachments/files/17950343/GCS.File.zip)

Let me know if you need more info/help, feel free to message me on Discord.

**Comment by StefanLeng** [comment]
Hmm, thats wired, it looks correct in my foundry:
![grafik](https://github.com/user-attachments/assets/818622fe-14ab-4a22-ba64-899f8198f1a2)
What browser are you using? Do you have maybe any non standard font or zoom settings in your browser?

**Comment by PrinceOfIonia** [comment]
@StefanLeng I do not use the browser version of FoundryVTT. I use the client version instead. I am on version 12 Stable Build 331. To my knowledge, all of my settings are default.

**Comment by StefanLeng** [comment]
That is the same as my setup. Strange...

**Comment by StefanLeng** [comment]
@PrinceOfIonia: I have no idea what to do with this one. It seems that the font in the attribute area is bigger as expected  on your screen shots, not leaving enough space for the move entry. But why....

You are not by any chance familar with CSS and the develoment console? It would really help to inspect the CSS of the elemnts in your world, but its hard to discribe how to do that

**Comment by PrinceOfIonia** [comment]
@StefanLeng I am a bit familiar with the console, just tell me what to do step by step and I'll try my best.

**Comment by StefanLeng** [comment]
Thats great!

1) Open the dev console wiht F12.

2) Activate the elemnt picker with this button:
![grafik](https://github.com/user-attachments/assets/aaf18396-eff2-43be-a4e3-e96d1169f2ff)

3) Pick one of the Attribute numbers.
![grafik](https://github.com/user-attachments/assets/6d40eb58-a783-4f95-afcf-ba539f706910)

4) That sould give you somthing like this in the console:
![grafik](https://github.com/user-attachments/assets/be8d910b-16f5-45bb-921a-0073ffb06a08)

5) Select everything in the right pane and copy and paste it into a text file. Make sure you scroll down all the way and select everything:
![grafik](https://github.com/user-attachments/assets/422c62cb-074c-4d11-83b1-fdb98b8623d1)

6) Switch to the "computed" tab on the right pane and make a screenshot like that:
![grafik](https://github.com/user-attachments/assets/0eeb9c64-9108-451a-a7e9-567ee853feaf)

7) Post the text file from step 5) and the screen shot from step 6) here.

Thank you!

**Comment by PrinceOfIonia** [comment]
https://pastebin.com/2rsm6FA8

![Screenshot_14](https://github.com/user-attachments/assets/ec3eb3a5-71fc-47ff-bbb2-cb8d75d00345)

Sorry for the delay, did I do everything correctly?

**Comment by StefanLeng** [comment]
No, Problem, that is exactly what I needed. I think I have figured out the difference.
It looks like you have this setting set to 6 (please check and let me know if I am wrong):

![grafik](https://github.com/user-attachments/assets/2d2646de-fd18-466e-95ac-0533ad20f0ab)

As far as I know 5 is the default.
I have to figure out how to account for different values in this setting.

**Comment by PrinceOfIonia** [comment]
@StefanLeng Looks like it works now, but I have a 2K monitor, making it hard to see text with the default font size of 5, and reducing the font size is not something I really want to do in order to use the sheet. Is there a way you can make the sheet work with different font sizes?

**Comment by StefanLeng** [comment]
I will definitly try, I consider ability to use bigger fonts important. It is a bit tricky, but at least for moderate increases it shoud be doable.

**Comment by StefanLeng** [comment]
I think I have it figured out. Needs a bit more testing, but will be in the next release.

**Comment by StefanLeng** [comment]
Fixed in 0.4.1
