### ISSUE TITLE
Feature Request: Multiple Arms

### ISSUE THREAD

**Issue by TheFabulousIronChef** [StefanLeng/gurps-categorized-sheet#2]
I had a thought, and wondered if having "Extra Arms" in GCS would trigger adding extra hands in the Categorized Sheet--no. This is pretty rare (Peshkali from DFM, the Deep Beyonder and Strix from DFM2, but they don't use weapons) and custom monsters (like this Dolgrim Warrior, which has 4 arms, two of which are generally using a crossbow and the other two shortsword and shield). 

Perhaps consider some kind of command that recognizes the Extra Arms trait and adds other hands automatically? Please note that as a non-programmer, I have no idea if this is trivially easy, impossibly difficult, or somewhere in between.

![image](https://github.com/user-attachments/assets/bdf8a239-ec8c-4b27-b544-9c87d9c479c4)

**Comment by StefanLeng** [comment]
I am aware of this issue, but have not descided yet how to do it. 
The code can handle any numbers of hands, but there are two issues:
1) I want to avoid parsing the advantages. I propably just make the number of hands a configuration item on the character.
2)  The trickier thing is to find a way to display more than two hands without breaking the layout ....

**Comment by StefanLeng** [comment]
Added with 0.3.2
