### ISSUE TITLE
Long equipment lists don't have a scrollbar

### ISSUE THREAD

**Issue by enlorca** [StefanLeng/gurps-categorized-sheet#3]
The project is pretty neat so far, it's handy for new players. Nonetheless, I have found a few issues that could be fixed.

One of the issues is that long equipment lists don't have a scrollbar in their tab, making some equipment inaccessible unless you resize the window.

Categorized sheet ↓↓

![image](https://github.com/user-attachments/assets/6f004ede-80f7-4fbc-9dd9-4326e53aa282)

Full view sheet ↓↓
![image](https://github.com/user-attachments/assets/db597570-d921-44c2-9aaa-d4fe334c57be)

Once again thanks for the sheet, it's very cool.

**Comment by StefanLeng** [comment]
Thank you for your kind words. I will add the scrollbar in the next release.

**Comment by StefanLeng** [comment]
Fixed with 0.3.2
