### ISSUE TITLE
Missing specific perception rolls in sheet (Vision, Hearing, Smell/Taste and Touch)

### ISSUE THREAD

**Issue by enlorca** [StefanLeng/gurps-categorized-sheet#4]
I love the minimalistic approach of the sheet, but I believe that in the box with the Perception roll there should be the option to roll for Vision, Hearing, Smell/Taste and Touch. They could have a smaller priority and use a smaller font, as to not distract from the other elements, but I believe that they should still be accessible.

![image](https://github.com/user-attachments/assets/2ec482ba-a74c-4fa4-a668-7360e3293eda)

**Comment by StefanLeng** [comment]
Hi, 
only those specific values that are different from Per are displayed. When displaying all 4, the layout breaks a  bit, but it is very unlikely that all 4 are different from per. 
If I display them all, I would need a heigher header (even with a much smaller font) and I like to avoid that. I could add a option to allways display them all and add a scrollbar, but that would be ugly...

**Comment by enlorca** [comment]
That's understandable. 
Maybe an alternative could be adding a box with the extended perception checks in the "Exploration & Stealth" tab? 
That way it won't break the layout.

**Comment by StefanLeng** [comment]
Thats a good Idea! I put it on the List.

**Comment by StefanLeng** [comment]
Added in 0.4.0
