### ISSUE TITLE
GCA character equipment not populating combat tab

### ISSUE THREAD

**Issue by darbymcd** [StefanLeng/gurps-categorized-sheet#6]
It seems as though it is not picking up some of the equipment to populate the combat tab.

[fvtt-Actor-murai'a-hartvigdottir-q0u67ntHEKe6VPoQ.json](https://github.com/user-attachments/files/17639733/fvtt-Actor-murai.a-hartvigdottir-q0u67ntHEKe6VPoQ.json)

[Murai_a Hartvigdottir export.txt](https://github.com/user-attachments/files/17639740/Murai_a.Hartvigdottir.export.txt)

I am not sure why I feel I have to give you screenshots so you believe me but here they are. It comes from having an IT dept that never believes anything I saw without screenshots, even if it is just a screenshot of a screen telling me my password is invalid....

![image](https://github.com/user-attachments/assets/d24bce2f-bbdd-4b15-8a95-f719a4e7e266)
![image](https://github.com/user-attachments/assets/af3a835c-13b1-4078-8361-cf0d14c38764)

**Comment by StefanLeng** [comment]
Did not handle the TL in the attack name correctly. The fix will be in the next release. Thank you for providing the character, I need to see as many characters as possible to find such border cases.

**Comment by StefanLeng** [comment]
Fixed in 0.4.0
