### ISSUE TITLE
Still having an issue with equpiment from GCA

### ISSUE THREAD

**Issue by darbymcd** [StefanLeng/gurps-categorized-sheet#7]
Hi, it is still not picking up all the info for equipment from GCA.
I have cat. sheet 0.4 installed
![image](https://github.com/user-attachments/assets/196d6096-c51d-44c0-9b27-c668efba30d6)
[Minati Kessler export.txt](https://github.com/user-attachments/files/17706978/Minati.Kessler.export.txt)
 
I am attaching the character as a txt export.

Thanks!

**Comment by StefanLeng** [comment]
Hmm, the extended Information in the equipment equipment name is missing. Odd, i don't think I do anything special with that. Dos it show up on the standard GGA Sheet?

Are you also missing attacks in the combat section (or somthing else)? 

It would be good if you could attach an JSON export from foundry (right click on the actor in the sidebar and chose export). That would allow me to debug the issue much more easily.

The GCA Export file for foundry would also work for me.

**Comment by darbymcd** [comment]
It does show up in the standard sheet. The attacks are there now, it is just the weight and cost data that I have noticed so far. 
I attached an export. hope that helps. 
    On Monday, November 11, 2024 at 01:54:00 PM GMT-5, StefanLeng ***@***.***> wrote:  
 
 


Hmm, the extendet Information in the equipment equipment name is missing. Odd, i don't think I do anything special with that. Dos it show up on the standard GGA Sheet?

Are you also missing attacks in the combat section (or somthing else)?

It would be good if you could attach an JSON export from foundry (right click on the actor in the sidebar and chose export). That would allow me to debug the issue much more easily.

The GCA Export file for foundry would also work for me.

**Comment by StefanLeng** [comment]
Thank you for the additiona Inforamtion, Unfortunaly, the attachment did not make it to Github vial Email. Could you try to upload it directly on Github? I aslo send you an DM on the GURPS Discord, if it is more convinient to send it per DM.
Sorry for the bother ...

**Comment by StefanLeng** [comment]
It turend out the issue is with the GCA import, not the sheet.
