### ISSUE TITLE
Bug: Trying to close a container with this sheet deletes it instead

### ISSUE THREAD

**Issue by PrinceOfIonia** [StefanLeng/gurps-categorized-sheet#8]
Exactly as title says, here is the GCS file. 
[GCS File.zip](https://github.com/user-attachments/files/17950189/GCS.File.zip)

**Comment by StefanLeng** [comment]
They are moved to the "Ohters" tab, but that should not be happening. I have to investigate why this happens with this character and not with my ohter test characters.

**Comment by StefanLeng** [comment]
Fixed in 0.4.1
