### ISSUE TITLE
Bug: Lifting and moving things chart breaks with high ST characters

### ISSUE THREAD

**Issue by PrinceOfIonia** [StefanLeng/gurps-categorized-sheet#9]
[GCS File.zip](https://github.com/user-attachments/files/17950202/GCS.File.zip)

Here is what the categorized sheet says:
![image](https://github.com/user-attachments/assets/186c6bdf-6120-4f06-ba8b-18e0d062b796)

Here is what GCS says: 
![image](https://github.com/user-attachments/assets/b266ff05-e0a4-4d84-ba13-691e555e3729)

**Comment by StefanLeng** [comment]
Hmm, the table on the standard GGA sheet ist also broken, but in a slightly different way. It could be a data import issue unrelated to the module. I have to investigate further.

**Comment by PrinceOfIonia** [comment]
Noted. I will make a bug report for GGA.

**Comment by StefanLeng** [comment]
The underlying issue  is parially fixed in GGA 0.17.16. While tis fix works for the standard GGA sheets where the values are reportet without unit, the full string including the unit is still broken.
I made a pull request to the GGA repository with a full fix.

**Comment by PrinceOfIonia** [comment]
You can close this BTW, GGA fixed this in their most recent update
